-- return {
--   -- lazy = true,
--   -- event = { "BufReadPre", "BufNewFile" }, -- to disable, comment this out
--   'mfussenegger/nvim-lint',
--   config = function()
--     local lint = require("lint")
--
--     lint.linters_by_ft = {
--       javascript = { "eslint_d" },
--       typescript = { "eslint_d" },
--       javascriptreact = { "eslint_d" },
--       typescriptreact = { "eslint_d" },
--     }
--
--     local lint_augroup = vim.api.nvim_create_augroup("lint", { clear = true })
--
--     vim.api.nvim_create_autocmd({ "BufEnter", "BufWritePost", "InsertLeave" }, {
--       group = lint_augroup,
--       callback = function()
--         lint.try_lint()
--       end,
--     })
--
--     -- vim.keymap.set("n", "<leader>l", function()
--     --   lint.try_lint()
--     -- end, { desc = "Trigger linting for current file" })
--   end,
-- }
return {}

-- return {
--   {
--     "neovim/nvim-lspconfig",
--     opts = {
--       --- other options
--       servers = {
--       tsserver = {
--         on_attach = function(client)
--           -- this is important, otherwise tsserver will format ts/js
--           -- files which we *really* don't want.
--           client.server_capabilities.documentFormattingProvider = false
--           end,
--         },
--         biome = {},
--         -- other language servers
--       },
--     },
--   },
--   {
--     "nvimtools/none-ls.nvim",
--     opts = function(_, opts)
--       local nls = require("null-ls").builtins
--       opts.sources = vim.list_extend(opts.sources or {}, {
--         nls.formatting.biome,
--
--         -- or if you like to live dangerously like me:
--         nls.formatting.biome.with({
--           args = {
--             'check',
--             '--apply-unsafe',
--             '--formatter-enabled=true',
--             '--organize-imports-enabled=true',
--             '--skip-errors',
--             '$FILENAME',
--           },
--         }),
--       })
--     end,
--   },
-- }
